spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newproject?characterEncoding=UTF-8
    username: root
    password: 12341234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

app:
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080